name: CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: FTP-Deploy-Action
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: "FTP Deployer"
        uses: sand4rt/ftp-deployer@v1.1
        with:
          host: ${{ secrets.FTP_SERVER }}
          port: 21 # optional
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_folder: src
          cleanup: false
          include: ''
          pasive: true # optional