name: CD
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    name: FTP-Deploy-Action
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2
        - name: FTP Deployer
          uses: sand4rt/ftp-deployer@v1.1
          with:
            # FTP host URL like: ftp.host.com
            host: ${{ secrets.FTP_SERVER }}
            # FTP port default is: 21
            port: 21 # optional
            # Ftp username
            username: ${{ secrets.FTP_USERNAME }}
            # Ftp password
            password: ${{ secrets.FTP_PASSWORD }}
            # The local folder location
            local_folder: src # optional, default is dist
            # Remove existing files inside FTP remote folder
            cleanup: false # optional
            include: '' # optional
            exclude: # optional
              - node_modules/**
              - node_modules/**/.*
              - .git/**
            pasive: true # optional