# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2
    
    - name: Upload
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: elev.htxroskilde.dk
        username: ${{ secrets.ftp_username }}
        password: ${{ secrets.ftp_password }}
        log-level: verbose
        protocol: ftps
        port: 21
